id: A2455A4B5
base_file: f00A6.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:38:31.956409
  last_modified_at: 2022-05-31 06:38:31.956415
