id: A2455A4B5
base_file: f9D6B.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:38:31.958560
  last_modified_at: 2022-05-31 06:38:31.958565
